export { default as AddIcon } from './add_round.png'
export { default as CloseIcon } from './close.png'
export { default as AddImageIcon } from './camera-create.png'
export { default as MarkerIcon } from './marker-xl.png'
export { default as GroupIcon } from './Group.png'
